#include "pluginManager.hpp"
#include "logger.hpp"
#include <ranges>
#include <algorithm>
#include <optional>
#include <sodium.h>
#include <nlohmann/json.hpp>
#include <fstream>
#include <fmt/format.h>

using json = nlohmann::json;

namespace gn {

// ─── Query ───────────────────────────────────────────────────────────────────

std::optional<handler_t*>
PluginManager::find_handler_by_name(std::string_view name) const {
    std::shared_lock lock(rw_mutex_);
    if (auto it = handlers_.find(name); it != handlers_.end()) {
        if (it->second->enabled) return it->second->handler;
        LOG_DEBUG("Handler '{}' found but disabled", name);
    }
    return std::nullopt;
}

std::optional<connector_ops_t*>
PluginManager::find_connector_by_scheme(std::string_view scheme) const {
    std::shared_lock lock(rw_mutex_);
    if (auto it = connectors_.find(scheme); it != connectors_.end())
        if (it->second->enabled) return it->second->ops;
    return std::nullopt;
}

size_t PluginManager::get_enabled_handler_count() const {
    std::shared_lock lock(rw_mutex_);
    return static_cast<size_t>(
        std::ranges::count_if(handlers_ | std::views::values,
                              [](const auto& i) { return i->enabled; }));
}

size_t PluginManager::get_enabled_connector_count() const {
    std::shared_lock lock(rw_mutex_);
    return static_cast<size_t>(
        std::ranges::count_if(connectors_ | std::views::values,
                              [](const auto& i) { return i->enabled; }));
}

void PluginManager::list_plugins() const {
    std::shared_lock lock(rw_mutex_);
    LOG_INFO("=== Handlers ({}) ===", handlers_.size());
    for (const auto& [name, info] : handlers_)
        LOG_INFO("  [{}] '{}' ({})",
                 info->enabled ? "ON " : "OFF", name, info->path.filename().string());
    LOG_INFO("=== Connectors ({}) ===", connectors_.size());
    for (const auto& [scheme, info] : connectors_)
        LOG_INFO("  [{}] {}:// -> '{}' ({})",
                 info->enabled ? "ON " : "OFF", scheme, info->name,
                 info->path.filename().string());
}

std::vector<handler_t*> PluginManager::get_active_handlers() const {
    std::shared_lock lock(rw_mutex_);
    std::vector<handler_t*> active;
    active.reserve(handlers_.size());
    for (const auto& [name, info] : handlers_)
        if (info->enabled && info->handler)
            active.push_back(info->handler);
    return active;
}

std::vector<connector_ops_t*> PluginManager::get_active_connectors() const {
    std::shared_lock lock(rw_mutex_);
    std::vector<connector_ops_t*> active;
    active.reserve(connectors_.size());
    for (const auto& [name, info] : connectors_)
        if (info->enabled && info->ops)
            active.push_back(info->ops);
    return active;
}

// ─── Verification ─────────────────────────────────────────────────────────────

/// @brief SHA-256 of file via libsodium streaming hash (64 KB buffer).
std::string PluginManager::calculate_sha256(const fs::path& path) {
    std::ifstream file(path, std::ios::binary);
    if (!file) return "";

    crypto_hash_sha256_state state;
    crypto_hash_sha256_init(&state);

    std::vector<char> buf(65536);
    while (file.read(buf.data(), buf.size()) || file.gcount() > 0) {
        crypto_hash_sha256_update(&state,
            reinterpret_cast<const unsigned char*>(buf.data()),
            static_cast<unsigned long long>(file.gcount()));
        if (file.eof()) break;
    }

    unsigned char out[crypto_hash_sha256_BYTES];
    crypto_hash_sha256_final(&state, out);

    std::string hex;
    hex.reserve(crypto_hash_sha256_BYTES * 2);
    for (auto b : out) fmt::format_to(std::back_inserter(hex), "{:02x}", b);
    return hex;
}

/// @brief Verify plugin JSON manifest (integrity.hash vs actual SHA-256).
/// @details Manifest: <plugin>.so.json — generated by buildPlugin.nix
std::expected<void, std::string>
PluginManager::verify_metadata(const fs::path& so_path) const {
    const fs::path json_path = so_path.string() + ".json";
    if (!fs::exists(json_path))
        return std::unexpected(
            fmt::format("Plugin manifest missing: {}", json_path.filename().string()));

    try {
        std::ifstream f(json_path);
        json data = json::parse(f);
        auto& meta = data.at("meta");

        LOG_DEBUG("Verifying: {} v{}",
                  meta.at("name").get<std::string>(),
                  meta.at("version").get<std::string>());

        const std::string expected = data.at("integrity").at("hash").get<std::string>();
        const std::string actual   = calculate_sha256(so_path);

        if (expected != actual)
            return std::unexpected(fmt::format(
                "Hash mismatch for '{}': expected {}..., got {}...",
                so_path.filename().string(),
                expected.substr(0, 8), actual.substr(0, 8)));

        return {};
    } catch (const std::exception& e) {
        return std::unexpected(fmt::format("Metadata parse error: {}", e.what()));
    }
}

// ─── State management ─────────────────────────────────────────────────────────

bool PluginManager::unload_handler(std::string_view name) {
    std::unique_lock lock(rw_mutex_);
    if (auto it = handlers_.find(name); it != handlers_.end()) {
        LOG_INFO("Unloading handler: '{}'", name);
        handlers_.erase(it);
        return true;
    }
    return false;
}

bool PluginManager::enable_handler(std::string_view name) {
    std::unique_lock lock(rw_mutex_);
    if (auto it = handlers_.find(name); it != handlers_.end()) {
        it->second->enabled = true;
        LOG_INFO("Handler '{}' enabled", name);
        return true;
    }
    return false;
}

bool PluginManager::disable_handler(std::string_view name) {
    std::unique_lock lock(rw_mutex_);
    if (auto it = handlers_.find(name); it != handlers_.end()) {
        it->second->enabled = false;
        LOG_INFO("Handler '{}' disabled", name);
        return true;
    }
    return false;
}

} // namespace gn
